import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const migration = readFileSync(
  new URL(
    "../prisma/migrations/20260808210000_add_portfolio_domain/migration.sql",
    import.meta.url,
  ),
  "utf8",
);
const evidenceMigration = readFileSync(
  new URL(
    "../prisma/migrations/20260812190000_add_planning_run_evidence/migration.sql",
    import.meta.url,
  ),
  "utf8",
);

describe("portfolio migration safety", () => {
  it("expands the Shift table without dropping or renaming it", () => {
    expect(migration).toContain('ALTER TABLE "Shift"');
    expect(migration).not.toContain('DROP TABLE "Shift"');
    expect(migration).not.toContain('ALTER TABLE "Shift" RENAME');
  });

  it("backfills generated allocations and protects historical relations", () => {
    expect(migration).toContain('WHERE "note" = \'Generated by CrewPlan scheduler\'');
    expect(migration).toContain('REFERENCES "Employee"("id") ON DELETE RESTRICT');
    expect(migration).toContain('REFERENCES "Project"("id") ON DELETE RESTRICT');
  });

  it("does not invent total budgets from weekly budgets", () => {
    expect(migration).toContain('ADD COLUMN "totalLaborBudgetCents" INTEGER');
    expect(migration).not.toMatch(/UPDATE\s+"Project"[\s\S]+"totalLaborBudgetCents"/);
  });

  it("adds nullable run evidence without rewriting historical planning runs", () => {
    expect(evidenceMigration).toContain('ALTER TABLE "PlanningRun"');
    expect(evidenceMigration).toContain('ADD COLUMN "evidence" JSONB');
    expect(evidenceMigration).not.toContain("NOT NULL");
    expect(evidenceMigration).not.toContain("UPDATE");
  });
});
